import type { MenuState } from "@/types/menu";

export const defaultMenuState: MenuState = {
  categories: [
    {
      id: "icecekler",
      name: "İçecekler",
      description: "Özenle demlenen kahveler, ferahlatıcı soğuk içecekler ve ev yapımı limonatalar.",
    },
    {
      id: "sutlu-tatlilar",
      name: "Sütlü Tatlılar",
      description: "Günlük sütle hazırlanan hafif, zarif ve dengeli tatlılar.",
    },
    {
      id: "kahvaltilar",
      name: "Kahvaltılar",
      description: "Çardak keyfine yakışan sıcak tabaklar, taze ürünler ve doyurucu seçenekler.",
    },
    {
      id: "atistirmaliklar",
      name: "Atıştırmalıklar",
      description: "Kahve arası paylaşmalıklar ve günün her saatine uyan küçük lezzetler.",
    },
  ],
  items: [
    {
      id: "cardak-latte",
      name: "Çardak Latte",
      category: "icecekler",
      description: "Yumuşak içimli espresso, kadifemsi süt köpüğü ve hafif vanilya dokunuşu.",
      price: 145,
      tags: ["Sıcak", "İmza"],
      featured: true,
    },
    {
      id: "damla-sakizli-turk-kahvesi",
      name: "Damla Sakızlı Türk Kahvesi",
      category: "icecekler",
      description: "Geleneksel Türk kahvesinin sakız aromasıyla zarif ve kalıcı yorumu.",
      price: 115,
      tags: ["Geleneksel"],
    },
    {
      id: "orman-meyveli-soguk-kahve",
      name: "Orman Meyveli Soğuk Kahve",
      category: "icecekler",
      description: "Cold brew, süt ve kırmızı meyve püresiyle ferah bir yaz klasiği.",
      price: 165,
      tags: ["Soğuk", "Yeni"],
    },
    {
      id: "sutlac",
      name: "Fırın Sütlaç",
      category: "sutlu-tatlilar",
      description: "Günlük süt, pirinç ve narin tarçınla taş fırın tadında kızarmış yüzey.",
      price: 135,
      tags: ["Günlük"],
      featured: true,
    },
    {
      id: "magnolia",
      name: "Çilekli Magnolia",
      category: "sutlu-tatlilar",
      description: "Vanilyalı krema, taze çilek ve ince bisküvi katmanları.",
      price: 155,
      tags: ["Soğuk"],
    },
    {
      id: "kazandibi",
      name: "Karamelize Kazandibi",
      category: "sutlu-tatlilar",
      description: "Yanık şeker aroması, yoğun süt lezzeti ve pürüzsüz kıvam.",
      price: 145,
      tags: ["Klasik"],
    },
    {
      id: "serpme-cardak",
      name: "Sütlü Çardak Serpmesi",
      category: "kahvaltilar",
      description: "Peynir seçkisi, zeytin, bal-kaymak, reçeller, sıcak pişi ve sınırsız çay.",
      price: 420,
      tags: ["2 kişilik"],
      featured: true,
    },
    {
      id: "menemen",
      name: "Bakır Tavada Menemen",
      category: "kahvaltilar",
      description: "Domates, biber, köy yumurtası ve isteğe bağlı kaşar peyniri.",
      price: 185,
      tags: ["Sıcak"],
    },
    {
      id: "avokado-tost",
      name: "Avokadolu Ekşi Maya Tost",
      category: "kahvaltilar",
      description: "Ekşi maya ekmeği, avokado kreması, beyaz peynir ve roka.",
      price: 210,
      tags: ["Hafif"],
    },
    {
      id: "peynirli-borek",
      name: "El Açması Peynirli Börek",
      category: "atistirmaliklar",
      description: "İnce hamur, lor-peynir karışımı ve yanında domates sosu.",
      price: 125,
      tags: ["Sıcak"],
    },
    {
      id: "kurabiye-tabagi",
      name: "Anne Kurabiyesi Tabağı",
      category: "atistirmaliklar",
      description: "Portakallı, kakaolu ve tarçınlı günlük kurabiye seçkisi.",
      price: 105,
      tags: ["Paylaşmalık"],
    },
    {
      id: "mini-sandvic",
      name: "Mini Çardak Sandviçleri",
      category: "atistirmaliklar",
      description: "Üçlü mini sandviç: füme hindi, beyaz peynir ve köz sebze.",
      price: 175,
      tags: ["Paylaşmalık"],
    },
  ],
};
